server:
  port: 8081

backend:
  base-url: http://localhost:8080
  endpoints:
    sim-cards: /api/public/sim-cards

jwt:
  secret: lhgadhkjfsaofewjvkbjvdksdfjefjfaejkkas
  lifetime: 30m

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: "/swagger-ui.html"
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
