services:
  postgres:
    image: postgres:17
    container_name: multiSimBox_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: multiSimBox
    ports:
      - "5433:5432"
    volumes:
      - multiSimBox_data:/var/lib/postgresql/data

  multisimbox:
    build:
      context: ./
    container_name: multiSimBox_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/multiSimBox
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

volumes:
  multiSimBox_data: